services:
  api:
    build:
      context: ./api
    image: api
    container_name: backend_api
    ports:
      - "5000:5000"
    networks:
      - saham_net

  extract_yfinance:
    build:
      context: . 
      dockerfile: extract/Dockerfile
    image: extraction  # Nama image yang digunakan
    container_name: extract_yfinance
    volumes:
      - ./output:/app/output  # Mount folder output dari host ke container
    environment:
      YFINANCE_OUTPUT_PATH: /app/output/yfinance_output.json
    command: ["python", "yfinance_extract.py"]  # Menjalankan yfinance_extract.py

  extract_idx:
    build:
      context: .  # Path to the root directory, not just extract
      dockerfile: extract/Dockerfile
    image: extraction
    container_name: extract_idx
    volumes:
      - ./output:/app/output
      - ./extract/idx_zip:/app/extract/idx_zip
      - ./extract/idx_extracted:/app/extract/idx_extracted
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 2G
    shm_size: '2G'  # Shared memory untuk Chrome
    restart: on-failure
    command: ["python3", "idx_extract.py"]

  extract_iqplus:
    build:
      context: .  
      dockerfile: extract/Dockerfile
    image: extraction  # Menggunakan image yang sama dengan extract_yfinance dan extract_idx
    container_name: extract_iqplus
    volumes:
      - ./output:/app/output
    environment:
      IQPLUS_OUTPUT_PATH: /app/output/iqplus_output.json
    command: ["python", "iqplus_extract.py"]  # Menjalankan iqplus_extract.py

  load_yfinance:
    build:
      context: ./load
      dockerfile: Dockerfile
    image: loader
    container_name: load_yfinance
    volumes:
      - ./output:/app/output
    command: ["python", "yfinance_load.py"]

networks:
  saham_net:
    driver: bridge
